[colors.bright]
black = "0x928374"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xebddb2"
yellow = "0xfabd2f"

[colors.dim]
black = "#32302f"
blue = "#076678"
cyan = "#427b58"
green = "#79740e"
magenta = "#8f3f71"
red = "#9d0006"
white = "#928374"
yellow = "#b57614"

[colors.normal]
black = "0x282828"
blue = "0x458588"
cyan = "0x689d6a"
green = "0x98971a"
magenta = "0xb16286"
red = "0xcc241d"
white = "0xa89984"
yellow = "0xd79921"

[colors.primary]
background = "0x1d2021"
bright_foreground = "#fbf1c7"
dim_foreground = "#a89984"
foreground = "0xebddb2"

[cursor]
blink_interval = 500
blink_timeout = 0

[cursor.style]
blinking = "Always"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold_italic]
family = "Terminus"
style = "Bold Italic"

[font.italic]
family = "Terminus"
style = "Italic"

[font.normal]
family = "Terminus"
style = "Regular"

[terminal.shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
decorations = "none"
title = "Alacritty"

[window.padding]
x = 3
y = 4

[terminal]
